name: upi_pay_latest
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  decimal: ^1.2.0
  universal_io: ^2.0.4

  cupertino_icons: ^1.0.8
  change_app_package_name: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  plugin:
    platforms:
      android:
        package: com.drenther.upi_pay
        pluginClass: UpiPayPlugin
      ios:
        pluginClass: UpiPayPlugin
  assets:
    - assets/apps/ios/

